export const paths = {
  root: "/",
  home: "/",
  aboutUs: "/about-us",
  allBike: "/all-bike",
  manageProducts: "manage-products",
  product: "/product",
  cart: "/carts",
  checkout: "/checkout",
  payment: "/payment",
  privacy: "/privacy-policy",
  terms: "/terms",
  contact: "/contact-us",
  compaire: "/compaire-bike",
  auth: {
    login: "/login",
    signup: "/signup",
  },
  bike: {
    root: "/bike",
  },
  account: {
    root: "/account",
    bikeList: "/account/bike-list",
    bikeAdmin: "/account/bike-lists",
    booking: "/account/booking",
    myRentals: "/account/my-rentals",
    rentals: "/account/rentals",
    users: "/account/users",
    coupon: "/account/coupon",
  },
};
